# Generated by Django 2.1.1 on 2018-10-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='start_date',
        ),
    ]
