# Generated by Django 2.1.1 on 2018-10-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_auto_20181014_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='image',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
