# Generated by Django 2.1.1 on 2018-10-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_auto_20181014_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
