# Generated by Django 2.1.1 on 2018-11-04 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_schedule_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='code_name',
            field=models.CharField(default='DEF', max_length=8),
        ),
    ]
