# Generated by Django 2.1.1 on 2018-11-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_transportation_code_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transportation',
            name='code_name',
        ),
        migrations.AddField(
            model_name='city',
            name='code_name',
            field=models.CharField(default='DEF', max_length=8),
        ),
    ]
