# Generated by Django 2.1.1 on 2018-11-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_auto_20181104_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
