# Generated by Django 2.1.1 on 2018-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_auto_20181104_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='account',
            name='phone_number',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AddField(
            model_name='schedule',
            name='cost_currency_format',
            field=models.CharField(default='IDR ', max_length=16),
        ),
    ]
