# Generated by Django 2.1.1 on 2018-11-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_place_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='logo',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='transportation',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
