# Generated by Django 2.1.1 on 2018-11-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_auto_20181113_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportation',
            name='capacity',
            field=models.IntegerField(default=180),
        ),
    ]
